#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

#Colorize ls output
alias ls='ls --color=auto'
alias ll='ls -lv'
alias la='ll -AF --group-directories-first'
alias lah='la -h'

#Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
