return {
    lspkind = {
        Text = "",
        Method = "m",
        Function = "",
        Constructor = "",
        Field = "",
        Variable = "",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        Keyword = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
        Copilot = "",
    },
    statusline_separators = {
        Default = {
            Left = "",
            Right = " ",
        },
        Round = {
            Left = "",
            Right = "",
        },
        Block = {
            left = "█",
            Right = "█",
        },
        Arrow = {
            Left = "",
            Right = "",
        },
    },
    git = {
        Added = "",
        Changed = "",
        Removed = "",
        Diff = "",
        Repo = "",
        Branch = "",
        Octoface = " ",
    },
    ui = {
        Bug = "",
        Stacks = "",
        Scopes = "",
        Watches = "",
        Search = " ",
        DebugConsole = "",
        Database = "",
        Calendar = "",
        Mail = "",
        LSP = "",
        LSP_Alt = "לּ",
        NewFile = "",
        Modified = "",
        FileTree = "פּ",
        Lock = "",
        Help = "",
        Lightbulb = "",
        NoteBook = "ﴬ",
        Git = "",
        GitHub = "",
        PackageInstalled = "",
        PackagePending = "",
        PackageUninstalled = "",
        PackageError = "",
        PackageMoved = "",
        Stethescope = "",
        Tab = "",
        Telescope = "",
        Target = "",
        Term = "",
        Tree = "",
        Tree_Alt = "侮",
        Vim = "",
        Wand = "",
        Close_Thin = "",
        Close_Circle_Filled = "",
        Close_Circle_Empty = "",
        Arrow_Left = "",
        Arrow_Right = "",
        Arrow_Up = "",
        Arrow_Down = "",
        Arrow_Circle_Left = "",
        Arrow_Circle_Right = "",
        Arrow_Circle_Up = "",
        Arrow_Circle_Down = "",
    },
    diagnostics = {
        Error = "",
        Warn = "",
        Info = "",
        Hint = "",
        Question = "",
    },
    dap = {
        Breakpoint = "",
        BreakpointCondition = "ﳁ",
        BreakpointRejected = "",
        LogPoint = "",
        Pause = "",
        Play = "",
        RunLast = "↻",
        StepBack = "",
        StepInto = "",
        StepOut = "",
        StepOver = "",
        Stopped = "",
        Terminate = "ﱢ",
    },
}
