# Use custom format:
format="$directory$git_branch$git_status$character"

# Prompt symbols 
[character]
success_symbol = "[](green bold)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
format = "[]($style)[[ ](bg:black fg:blue )$path](bg:black fg:white)[ ]($style)"
style = "bg:none fg:black"

[git_branch]
format = "[]($style)[[ ](bg:black fg:bright-red)$branch](bg:black fg:white)[ ]($style)"
style = "bg:none fg:black"

[git_status]
format = "([]($style)[$all_status$ahead_behind](bg:black fg:bold red)[ ]($style))"
style = "bg:none fg:black"

